name: meal_monkey
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
#  google_fonts: ^4.0.3
  flutter_svg: ^2.0.1
  flutter_osm_plugin: ^0.42.0
  geolocator: ^9.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  logger: ^1.2.2
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
   - assets/images/

  fonts:
     - family: Metropolis
       fonts:
         - asset: assets/fonts/Metropolis-Bold.otf
           weight: 700
         - asset: assets/fonts/Metropolis-SemiBold.otf
           weight: 600
         - asset: assets/fonts/Metropolis-Medium.otf
           weight: 500
         - asset: assets/fonts/Metropolis-Regular.otf
           weight: 400
         - asset: assets/fonts/Metropolis-Light.otf
           weight: 300

